// Code generated by mockery v2.6.0. DO NOT EDIT.

package handlers

import (
	context "context"
	service "kznexp/service"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Process provides a mock function with given fields: ctx, batch, tasks
func (_m *MockService) Process(ctx context.Context, batch *service.Batch, tasks chan *service.Item) error {
	ret := _m.Called(ctx, batch, tasks)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.Batch, chan *service.Item) error); ok {
		r0 = rf(ctx, batch, tasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
